name: my_portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
    - assets/avatar1.png
    - assets/icons/call.png
    - assets/icons/whatsapp.png
    - assets/icons/email.png
    - assets/icons/linkedin.png
    - assets/icons/github.png
    - assets/icons/vedioConf.png
    - assets/projects/AcademiCore.png
    - assets/projects/Gitos.png
    - assets/projects/JS_DOM.png